---
title: "method"
author: "Tahmid Ahmed"
date: "5/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
# Load libraries
library(tidyverse)
library(ggplot2)
library(janitor)
library(wbstats)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
libraries <- c("pdftools", "tm", "ggraph", "tidyr", "graphlayouts", "lsa", "SnowballC", "ldatuning", 
               "topicmodels", "ggplot2", "dplyr", "rjson", "quanteda", "lubridate",
               "parallel", "doParallel", "tidytext", "stringi", "Rmpfr", "data.table", "survival")

lapply(libraries, require, character.only = TRUE)
```


```{r}
# Middle + High Income Countries
countries <- wbstats::wbcountries()
countries <- countries[-which(countries$region == "Aggregates"),]

countries <- countries %>% dplyr::select(country, income) %>%
  filter(income != "Low income") %>%
  filter(income != "Lower middle income") 


countries$country <- countrycode::countrycode(countries$country, origin = "country.name", destination = "iso2c")

# Load ethics data
ethics <- read_csv("/Users/tahmidahmed/Desktop/gov_97paper/gov97_paper/data/ethics_papers.csv") %>%
  filter(`Type of Document` %in%  c("Government Agency", "Intergovernmental Organization/Agency")) 

ethics <- as.data.frame(table(ethics$Country)) %>%
  rename("Country Name" = Var1)
  
ethics$country <- countrycode::countrycode(ethics$`Country Name`, origin = "country.name", destination = "iso2c")

ethics <- ethics %>% select(country, Freq)

# Load business data
business <- read_csv("/Users/tahmidahmed/Desktop/gov_97paper/gov97_paper/data/business_ranking.csv") %>%
  select("2019", "Country Code") %>%
  rename("ranking" = "2019")

business$country <- countrycode::countrycode(business$`Country Code`, origin = "wb", destination = "iso2c")

business <- business %>%
  select(country, ranking)

# Load GDP data
GDP <- read_csv("/Users/tahmidahmed/Desktop/gov_97paper/gov97_paper/data/GDP.csv") %>%
  select('2019', 'Country Code') %>%
  rename("gdp" = "2019")

GDP$country <- countrycode::countrycode(GDP$`Country Code`, origin = "wb", destination = "iso2c")

GDP <- GDP %>%
  select(country, gdp)

# Load innovation data
innovation <- read_csv("/Users/tahmidahmed/Desktop/gov_97paper/gov97_paper/data/innovation.csv") %>%
  rename("innovation" = "Score", "Country Name" = "Economy") %>%
    select('Country Name', innovation)

innovation$country <- countrycode::countrycode(innovation$`Country Name`, origin = "country.name", destination = "iso2c")

innovation <- innovation %>%
  select(country, innovation)


# Load learning data
atop <- data.table::fread("/Users/tahmidahmed/Desktop/gov_97paper/gov97_paper/data/atop5_0sy.csv")

atop <- atop %>% filter(year > 1996) 

atop$etreaty <- ifelse(is.na(atop$atopid13), 0, 1)

atop$country <- countrycode::countrycode(atop$state, origin = "cown", destination = "iso2c")

atop <- atop %>% dplyr::select(number, country, year) %>%
  filter(year == 2018) %>%
  rename("alliances" = "number")

atop <- atop %>%
  select("country", "alliances")


# Load polity data
polity <- read_csv("/Users/tahmidahmed/Desktop/gov_97paper/gov97_paper/data/polity.csv") %>%
  select(country, year, polity, polity2, ccode, scode) %>%
  rename("Country Name" = "country")  %>%
  filter(year == 2018)

polity$country <- countrycode::countrycode(polity$`ccode`, origin = "p4n", destination = "iso2c")

polity <- polity %>%
  select(country, polity, polity2)


# Throw in zero cases, throw out low-income countries, 
```

```{r}
# Join data
bus_ethics <- business %>% left_join(GDP) 
bus_ethics <- bus_ethics %>% left_join(innovation)
bus_ethics <- bus_ethics %>% left_join(atop)
bus_ethics <- bus_ethics %>% left_join(polity)
bus_ethics <- bus_ethics %>% left_join(countries)


bus_ethics <- bus_ethics %>%
  na.omit()

bus_ethics <- bus_ethics %>%
  left_join(ethics)

bus_ethics <- bus_ethics %>%
   mutate(Freq = replace_na(Freq, 0))

bus_ethics$cname <- countrycode::countrycode(bus_ethics$country, origin = "iso2c", destination = "country.name")

```

```{r}
# Economics model
# lm1 <- lm(Freq ~ gdp*ranking + innovation, data = bus_ethics)
# summary(lm1)

lm1 <- lm(Freq ~ gdp + ranking + innovation, data = bus_ethics)
summary(lm1)
```


```{r}
# Create learning model
#lm2 <- lm(Freq ~ alliances*polity + innovation, data = bus_ethics)
# summary(lm2)

lm2 <- lm(Freq ~ alliances + polity + innovation, data = bus_ethics)
summary(lm2)
```


throw in zeros, take out low-income, and should be about 139 countries

instead of recoding the other datasets, recode ethics first

Fit all the ones that are signficiant to a thid regression so might not

countries <- wbstats::wbcountries()
countries <- countries[-which(countries$region == "Aggregates"),]

countries <- countries %>% dplyr::select(country, income, region)
mutate(Freq = replace_na(Freq, 0))



